version: '3.8'

services:
  nlp-service:
    build: .
    container_name: nlp-microservice
    ports:
      - "8161:8161"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8161
      - LOG_LEVEL=INFO
      - MAX_WORKERS=10
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import grpc; channel = grpc.insecure_channel('localhost:8161'); grpc.channel_ready_future(channel).result(timeout=10)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy for load balancing
  nginx:
    image: nginx:alpine
    container_name: nlp-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nlp-service
    restart: unless-stopped
